inherit_from: .rubocop_todo.yml




AllCops:
  NewCops: enable
  Exclude:
    - 'data/customers.csv'
    - 'utility_scripts/**'

Style/HashSyntax:
  Enabled: false

Layout/SpaceAroundKeyword:
  Enabled: false