require 'rspec'
require 'simplecov'
SimpleCov.start
require './lib/merchant_repository'
require './lib/merchant'
require './lib/sales_engine'
require './lib/item_repository'
require './lib/item'
require './lib/invoice'
require './lib/invoice_repository'
require './lib/transaction'
require './lib/transaction_repository'
